#!/bin/bash

sudo apt-get update && sudo apt-get install -y wget git build-essential squashfs-tools \
                                                    libtool \
                                                    autotools-dev \
                                                    automake \
                                                    autoconf \
                                                    uuid-dev \
                                                    libssl-dev \
                                                    libarchive-dev


sudo sed -i -e 's/^Defaults\tsecure_path.*$//' /etc/sudoers

if [ "${PYTHON_VERSION}" == "2" ];
then
    wget https://repo.continuum.io/archive/Anaconda2-5.0.0.1-Linux-x86_64.sh
    sudo bash Anaconda2-5.0.0.1-Linux-x86_64.sh -b -p /opt/anaconda2 && sudo chown -R 0755 /opt/anaconda2
    PATH=/opt/anaconda3/bin:$PATH
    rm Anaconda2-5.0.0.1-Linux-x86_64.sh 
    export PATH
else
    wget https://repo.continuum.io/archive/Anaconda3-5.0.0.1-Linux-x86_64.sh
    sudo bash Anaconda3-5.0.0.1-Linux-x86_64.sh -b -p /opt/anaconda3 && sudo chown -R 0755 /opt/anaconda3
    PATH=/opt/anaconda3/bin:$PATH
    rm Anaconda3-5.0.0.1-Linux-x86_64.sh
    export PATH
fi

# Install python dependencies
which python

conda install -y pandas scikit-learn pygments
cd $TRAVIS_BUILD_DIR && sudo python -m pip install -r requirements.txt
/opt/anaconda3/bin/pip uninstall singularity --yes || echo "Not installed"
/opt/anaconda3/bin/python setup.py install

# Install Singularity

SINGULARITY_BASE="${GOPATH}/src/github.com/sylabs/singularity"
export PATH="${GOPATH}/bin:${PATH}"

mkdir -p "${GOPATH}/src/github.com/sylabs"
cd "${GOPATH}/src/github.com/sylabs"

git clone -b release-3.2 https://github.com/sylabs/singularity
cd singularity
./mconfig -v -p /usr/local
make -j `nproc 2>/dev/null || echo 1` -C ./builddir all
sudo make -C ./builddir install
